name: aitana
description: "Aitana – E-Waste Upcycling Assistant."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_fonts: ^4.0.4
  timezone: ^0.9.2
  http: ^1.4.0
  image_picker: ^1.0.4
  url_launcher: ^6.1.12
  intl: ^0.18.1
  provider: ^6.1.0

  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  

